import { useState, useEffect, useCallback } from 'react'
import './ResultsPanel.css'

const SECTIONS = [
  {
    key: 'suspension',
    label: 'Suspension',
    icon: '⚙',
    fields: [
      { key: 'front_height',             label: 'Ride Height (F)',       unit: 'mm' },
      { key: 'rear_height',              label: 'Ride Height (R)',       unit: 'mm' },
      { key: 'front_spring_rate',        label: 'Spring Rate (F)',       unit: 'N/mm' },
      { key: 'rear_spring_rate',         label: 'Spring Rate (R)',       unit: 'N/mm' },
      { key: 'front_arb',                label: 'Anti-Roll Bar (F)',     unit: '' },
      { key: 'rear_arb',                 label: 'Anti-Roll Bar (R)',     unit: '' },
      { key: 'front_damper_compression', label: 'Damper Comp. (F)',      unit: '' },
      { key: 'rear_damper_compression',  label: 'Damper Comp. (R)',      unit: '' },
      { key: 'front_damper_extension',   label: 'Damper Ext. (F)',       unit: '' },
      { key: 'rear_damper_extension',    label: 'Damper Ext. (R)',       unit: '' },
      { key: 'front_camber',             label: 'Camber (F)',            unit: '°' },
      { key: 'rear_camber',              label: 'Camber (R)',            unit: '°' },
      { key: 'front_toe',                label: 'Toe (F)',               unit: '°' },
      { key: 'rear_toe',                 label: 'Toe (R)',               unit: '°' },
    ],
  },
  {
    key: 'aero',
    label: 'Aerodynamics',
    icon: '〰',
    fields: [
      { key: 'front_downforce', label: 'Front Downforce', unit: '' },
      { key: 'rear_downforce',  label: 'Rear Downforce',  unit: '' },
    ],
  },
  {
    key: 'brakes',
    label: 'Brakes',
    icon: '◉',
    fields: [
      { key: 'balance',        label: 'Brake Balance',   unit: '' },
      { key: 'front_pressure', label: 'Front Pressure',  unit: '' },
      { key: 'rear_pressure',  label: 'Rear Pressure',   unit: '' },
    ],
  },
  {
    key: 'lsd',
    label: 'LSD',
    icon: '↻',
    fields: [
      { key: 'initial_torque',    label: 'Initial Torque',    unit: '' },
      { key: 'accel_sensitivity', label: 'Accel Sensitivity', unit: '' },
      { key: 'decel_sensitivity', label: 'Decel Sensitivity', unit: '' },
    ],
  },
  {
    key: 'tyres',
    label: 'Tyres',
    icon: '○',
    fields: [
      { key: 'front', label: 'Front Compound', unit: '' },
      { key: 'rear',  label: 'Rear Compound',  unit: '' },
    ],
  },
  {
    key: 'transmission',
    label: 'Transmission',
    icon: '⇌',
    fields: [
      { key: 'final_gear', label: 'Final Gear Ratio', unit: '' },
    ],
  },
]

// ── Helpers ──────────────────────────────────────────────────────────────────

/** Build plain-text representation of a setup for clipboard copy. */
function buildCopyText(title, car, track, setup) {
  const lines = [`${title} — ${car} at ${track}`, '']
  for (const section of SECTIONS) {
    const data = setup?.[section.key] ?? {}
    const visible = section.fields.filter((f) => data[f.key] && data[f.key] !== 'N/A')
    if (!visible.length) continue
    lines.push(`── ${section.label} ──`)
    for (const field of visible) {
      lines.push(`  ${field.label}: ${data[field.key]}${field.unit}`)
    }
    lines.push('')
  }
  if (setup?._source_url) lines.push(`Source: ${setup._source_url}`)
  lines.push('\nGenerated by GT7 Setup Finder (gt7setup.app)')
  return lines.join('\n')
}

// ── Sub-components ───────────────────────────────────────────────────────────

function SetupSection({ section, setup }) {
  const sectionData = setup?.[section.key] ?? {}
  const visibleFields = section.fields.filter(
    (f) => sectionData[f.key] && sectionData[f.key] !== 'N/A',
  )
  if (!visibleFields.length) return null

  return (
    <div className="setup-section">
      <div className="setup-section__title">
        <span className="setup-section__icon" aria-hidden="true">{section.icon}</span>
        {section.label}
      </div>
      <table className="setup-table">
        <tbody>
          {visibleFields.map((field) => (
            <tr key={field.key} className="setup-table__row">
              <td className="setup-table__label">{field.label}</td>
              <td className="setup-table__value">
                {sectionData[field.key]}
                {field.unit && <span className="setup-table__unit">{field.unit}</span>}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

function CopyButton({ title, car, track, setup }) {
  const [copied, setCopied] = useState(false)

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(buildCopyText(title, car, track, setup))
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // clipboard API unavailable — silently ignore
    }
  }, [title, car, track, setup])

  return (
    <button
      className={`copy-btn${copied ? ' copy-btn--copied' : ''}`}
      onClick={handleCopy}
      title="Copy setup to clipboard"
      aria-label="Copy setup to clipboard"
    >
      {copied ? (
        <>
          <svg width="13" height="13" viewBox="0 0 14 14" fill="none" aria-hidden="true">
            <path d="M2.5 7.5L5.5 10.5L11.5 4" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/>
          </svg>
          Copied!
        </>
      ) : (
        <>
          <svg width="13" height="13" viewBox="0 0 14 14" fill="none" aria-hidden="true">
            <rect x="1.5" y="4.5" width="8" height="9" rx="1.5" stroke="currentColor" strokeWidth="1.3"/>
            <path d="M4.5 4V3a1.5 1.5 0 0 1 1.5-1.5h5A1.5 1.5 0 0 1 12.5 3v7a1.5 1.5 0 0 1-1.5 1.5H10" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round"/>
          </svg>
          Copy
        </>
      )}
    </button>
  )
}

function SetupColumn({ title, type, car, track, setup }) {
  if (!setup)
    return (
      <div className={`setup-col setup-col--${type}`}>
        <div className="setup-col__header">
          <span className="setup-col__badge">{type}</span>
          <h2>{title}</h2>
        </div>
        <p className="setup-col__none">No {type} setup found.</p>
      </div>
    )

  return (
    <div className={`setup-col setup-col--${type}`}>
      <div className="setup-col__header">
        <span className="setup-col__badge">{type}</span>
        <h2>{title}</h2>
        <CopyButton title={title} car={car} track={track} setup={setup} />
      </div>

      <div className="setup-col__body">
        {SECTIONS.map((section) => (
          <SetupSection key={section.key} section={section} setup={setup} />
        ))}

        {setup._source_url && (
          <a
            className="setup-col__source"
            href={setup._source_url}
            target="_blank"
            rel="noreferrer"
          >
            <span>View source thread</span>
            <svg width="11" height="11" viewBox="0 0 12 12" fill="none" aria-hidden="true">
              <path
                d="M2.5 9.5L9.5 2.5M9.5 2.5H4.5M9.5 2.5V7.5"
                stroke="currentColor"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          </a>
        )}
      </div>
    </div>
  )
}

// ── Loading state with elapsed timer ─────────────────────────────────────────

function LoadingState() {
  const [elapsed, setElapsed] = useState(0)

  useEffect(() => {
    const id = setInterval(() => setElapsed((s) => s + 1), 1000)
    return () => clearInterval(id)
  }, [])

  const hint =
    elapsed < 5
      ? 'Searching GTPlanet community threads…'
      : elapsed < 15
        ? 'Generating setup recommendations…'
        : elapsed < 30
          ? 'Almost there — AI is finalising values…'
          : 'Taking a bit longer than usual, hang tight…'

  return (
    <div className="results-empty">
      <div className="results-loading">
        <div className="results-loading__spinner" />
        <p>{hint}</p>
        <span className="results-loading__timer">{elapsed}s</span>
        <span className="results-loading__note">
          First lookup takes 15–30 s. Results are cached after that.
        </span>
      </div>
    </div>
  )
}

// ── Main export ──────────────────────────────────────────────────────────────

export default function ResultsPanel({ car, track, results, searched, loading, error, onRetry }) {
  if (!searched) {
    return (
      <div className="results-empty">
        <div className="results-empty__content">
          <div className="results-empty__flag" aria-hidden="true">
            {Array.from({ length: 16 }).map((_, i) => <span key={i} />)}
          </div>
          <h2 className="results-empty__heading">Find Your Perfect Setup</h2>
          <p className="results-empty__sub">
            Select a car and track above, then click{' '}
            <strong>Find Setups</strong> to get AI-powered tuning recommendations
            sourced from the GTPlanet community.
          </p>
          <div className="results-empty__chips">
            <span className="results-empty__chip results-empty__chip--aggressive">Aggressive</span>
            <span className="results-empty__chip--sep">vs</span>
            <span className="results-empty__chip results-empty__chip--safe">Safe</span>
          </div>
        </div>
      </div>
    )
  }

  if (loading) return <LoadingState />

  if (error) {
    return (
      <div className="results-empty">
        <div className="results-error">
          <div className="results-error__icon">✕</div>
          <p>Could not find setups</p>
          <span>{error}</span>
          {onRetry && (
            <button className="results-error__retry" onClick={onRetry}>
              Try Again
            </button>
          )}
        </div>
      </div>
    )
  }

  return (
    <div className="results-panel">
      <div className="results-panel__heading">
        <span className="results-panel__car">{car?.label}</span>
        <span className="results-panel__sep">at</span>
        <span className="results-panel__track">{track?.label}</span>
        {results?.source === 'cache' && (
          <span className="results-panel__cache-badge" title="Loaded from local cache">
            <svg width="9" height="9" viewBox="0 0 12 12" fill="none" aria-hidden="true">
              <path d="M6 1v3.5L8 6" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
              <circle cx="6" cy="6" r="4.5" stroke="currentColor" strokeWidth="1.5"/>
            </svg>
            cached
          </span>
        )}
      </div>

      <div className="results-panel__grid">
        <SetupColumn
          title="Aggressive Setup"
          type="aggressive"
          car={car?.label}
          track={track?.label}
          setup={results?.aggressive}
        />
        <div className="results-panel__divider" />
        <SetupColumn
          title="Safe Setup"
          type="safe"
          car={car?.label}
          track={track?.label}
          setup={results?.safe}
        />
      </div>
    </div>
  )
}
